services:
  db :
    container_name: woodstock_db
    image: postgres:alpine
    environment:
      POSTGRES_DB: woodstock_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5435:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    container_name: woodstock_redis
    image: 'redis:alpine'
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  pgdata:
  redis_data: