spring.application.name=woodstock.com
spring.config.import=env.properties

server.port=${APP_PORT}
spring.data.web.pageable.serialization-mode=via-dto

#config jpa

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${DB_URL}${DB_NAME}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

#config spring data mongo

spring.mongodb.username=rinmaa
spring.mongodb.password=rinmaa
spring.mongodb.host=localhost
spring.mongodb.port=27070
spring.mongodb.database=woodstock_com
spring.mongodb.authentication-database=admin

#config redist

spring.cache.type=redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

logging.level.org.springframework.cache=TRACE
logging.level.org.springframework.security = trace;

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

jwt.secret.key=${SECRET_KEY}
jwt.expiration.access.dev=${ACCESS_EXP_DEV}
jwt.expiration.access.production=${ACCESS_EXP_PROD}

